<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('penyakit_solusi', function (Blueprint $table) {
            $table->id(); // Add this line to create an 'id' column as the primary key
            $table->string('nama_penyakit', 100)->nullable();
            $table->text('definisi')->nullable();
            $table->text('solusi')->nullable();
            $table->text('tindak_lanjut');
            $table->text('obat');
            $table->integer('priority');
            $table->timestamps();
        });

        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'Gastritis atau Maag',
                'definisi' => 'Gastritis adalah peradangan pada lapisan lambung yang terjadi secara akut/kronis. Penyebab gastritis adalah terlalu banyak minum-minuman beralkohol, penggunaan jangka panjang atau dalam dosis tinggi obat aspirin dan ibuprofen, stres berat atau trauma, infeksi bakteri atau virus seperti infeksi Helicobacter pylori (H.pylori). Gejala gastritis adalah gangguan pencernaan, perut kembung, mual, dan muntah.',
                'solusi' => 'Perubahan gaya hidup dan pola makan: \r\n\r\n* hindari makanan pedas, kecut, asam. Serta minuman yang mengandung kafein (teh/Kopi) dan minuman bersoda.\r\n* Mengkonsumsi makanan kecil sepanjang hari daripada makan besar dapat membantu mengurangi produksi asam lambung dan mencegah peregangan lambung yang berlebihan.\r\n* Kelebihan berat badan dapat meningkatkan tekanan pada perut, yang menyebabkan gejala. Olahraga teratur dan diet seimbang dapat membantu mencapai dan mempertahankan berat badan yang sehat.\r\n* Melakukan aktivitas yang dapat mengurangi stres seoerti olahraga, meditasi, hobi atau suatu hal yang bermanfaat.\r\n',
                'tindak_lanjut' => '1. Pemeriksaan rutin: Jadwalkan janji tindak lanjut dengan penyedia layanan kesehatan Anda untuk mengevaluasi respons Anda terhadap pengobatan dan menilai penyembuhan lapisan perut. Mereka mungkin akan melakukan tes atau pemeriksaan lebih lanjut untuk memantau kondisi Anda.\r\n\r\n2. Manajemen obat: Jika Anda telah diresepkan obat untuk gastritis, ikuti dosis dan durasi pengobatan yang dianjurkan. Beri tahu dokter Anda tentang efek samping atau kekhawatiran yang mungkin Anda miliki. Mereka mungkin menyesuaikan rejimen pengobatan Anda jika diperlukan.\r\n\r\n3. Modifikasi gaya hidup: Terus patuhi perubahan gaya hidup yang direkomendasikan. Ini mungkin termasuk menghindari makanan pemicu, mengurangi konsumsi alkohol, mengelola stres, dan menjaga pola makan dan berat badan yang sehat.\r\n\r\n4. Mengelola gejala: Jika Anda masih mengalami gejala meskipun sudah diobati, diskusikan hal ini dengan penyedia layanan kesehatan Anda. Mereka mungkin menyarankan tindakan tambahan atau penyesuaian pada rencana perawatan Anda.\r\n\r\n5. Tes lanjutan: Dalam beberapa kasus, dokter Anda mungkin merekomendasikan tes lanjutan untuk menilai efektivitas pengobatan atau untuk memeriksa adanya infeksi H. pylori. Ini mungkin melibatkan tes napas, tes feses, atau endoskopi.\r\n\r\n6. Pencegahan komplikasi: Gastritis, jika tidak diobati atau dikelola dengan buruk, dapat menyebabkan komplikasi seperti tukak lambung atau perdarahan gastrointestinal. Perawatan tindak lanjut secara teratur membantu mengidentifikasi dan mengatasi potensi komplikasi secara tepat waktu.',
                'obat' => '1. Golongan antasida dapat membantu menetralkan asam lambung dan meredakan gejala untuk sementara :\r\n* Sediaan tablet bisa 1-2 tablet, 3 hingga 4x sehari, tablet dikunyah dahulu sebelum ditelan agar terlarut dengan baik. \r\n* Sediaan syrup 10-20ml dapat diminum 4xsehari, 20 menit - 1 jam setelah makan dan saat sebelum tidur, maksimal 80ml/hari.\r\n\r\n2. Golongan H2 Blocker, obat-obatan ini memblokir aksi histamin, yang merangsang produksi asam lambung :\r\n* Rebamipide dapat diberikan 100mg 3xsehari.\r\n\r\n3. Golongan Proton Pump Inhibitor, obat-obatan ini mengurangi produksi asam lambung dan meningkatkan penyembuhan lapisan lambung :\r\n* Omeprazole dapat diberikan 20-40mg 1xsehari.\r\n* Lansoprazole dapat diberikan 30mg 1xsehari.\r\n* Esomeprazole dapat diberikan 20-40mg 1xsehari.\r\n\r\n4. Antibiotik: Jika gastritis disebabkan oleh infeksi bakteri Helicobacter pylori (H. pylori), kombinasi antibiotik dapat diresepkan untuk membasmi infeksi. Antibiotik yang biasa digunakan untuk H. pylori termasuk klaritromisin, amoksisilin, dan metronidazol.\r\n\r\n5. Agen Cytoprotective: Obat-obatan ini membantu melindungi lapisan perut dari kerusakan dan meningkatkan penyembuhan. Contohnya termasuk sukralfat dan misoprostol.',
                'priority' => '1',
            )
        );
        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'GERD (Gastro Esophageal Reflux Disease)',
                'definisi' => 'GERD adalah kondisi kronis yang terjadi ketika asam lambung dan terkadang empedu mengalir kembali ke kerongkongan. Aliran mundur ini dikenal sebagai refluks asam. Disertai gejala seperti nyeri dada, kesulitan menelan, batuk kronis, suara serak/sakit tenggorokan',
                'solusi' => '1. Menjaga berat badan yang sehat: Jika Anda kelebihan berat badan, mengurangi berat badan dapat membantu mengurangi tekanan pada perut dan mengurangi gejala GERD.\r\n\r\n2. Hindari makanan pemicu: Identifikasi makanan atau minuman yang memperburuk gejala GERD bagi Anda, seperti makanan berlemak, pedas, asam, kafein, atau alkohol, dan hindarilah konsumsinya.\r\n\r\n3. Hindari makan berlebihan: Makan dalam porsi yang lebih kecil dan menghindari makan terlalu cepat dapat membantu mencegah peningkatan tekanan pada perut dan mencegah reflux.\r\n\r\n4. Menghindari makan sebelum tidur: Usahakan untuk tidak makan dalam dua hingga tiga jam sebelum tidur agar lambung tidak terisi saat berbaring, mengurangi risiko reflux.\r\n\r\n5. Makan dengan posisi yang tegak: Makan dengan posisi yang tegak dan duduk selama setidaknya 30 menit setelah makan dapat membantu mencegah reflux.\r\n\r\n6. Mengangkat kepala tempat tidur: Menambahkan beberapa bantal di bawah kepala tempat tidur Anda atau menggunakan bantal khusus untuk meninggikan posisi kepala saat tidur dapat membantu mencegah reflux saat berbaring.\r\n\r\n7. Menghindari merokok: Merokok dapat merelaksasi otot sfingter esofagus bawah (LES) yang bertanggung jawab menjaga agar asam lambung tidak naik ke esofagus. Menghentikan kebiasaan merokok dapat membantu mengurangi gejala GERD.\r\n\r\n8. Menghindari pakaian ketat: Mengenakan pakaian yang ketat dapat menekan perut dan meningkatkan risiko reflux. Menggunakan pakaian yang longgar dan nyaman dapat membantu mengurangi gejala GERD.',
                'tindak_lanjut' => 'Beberapa langkah tindak lanjut yang mungkin direkomendasikan :\r\n1. Mengikuti rencana pengobatan\r\n\r\n2. Evaluasi dan penyesuaian: Secara teratur kembali untuk pemeriksaan dengan dokter Anda untuk mengevaluasi efektivitas pengobatan. Jika gejala tidak terkendali atau ada perubahan dalam kondisi Anda, dokter mungkin perlu menyesuaikan dosis obat atau meresepkan obat yang berbeda.\r\n\r\n3. Perubahan gaya hidup yang berkelanjutan: Terus menerapkan perubahan gaya hidup yang telah direkomendasikan, seperti menjaga berat badan yang sehat, menghindari makanan pemicu, makan dengan posisi yang tegak, menghindari makan sebelum tidur, dan menghentikan kebiasaan merokok. Perubahan gaya hidup yang konsisten dan berkelanjutan dapat membantu mengontrol gejala GERD.\r\n\r\n4. Manajemen stres: Stres dapat mempengaruhi gejala GERD. Cari cara untuk mengelola stres, seperti dengan berolahraga, meditasi, atau terapi relaksasi. Mengembangkan strategi pengelolaan stres yang efektif dapat membantu mengurangi frekuensi dan keparahan gejala GERD.\r\n\r\n5. Diet yang sehat: Terapkan pola makan sehat yang mencakup makanan yang rendah lemak, rendah pedas, rendah asam, dan tinggi serat. Hindari makanan atau minuman yang memperburuk gejala GERD. Makan dengan porsi kecil dan sering dapat membantu mencegah peningkatan tekanan pada perut.\r\n\r\n6. Pemantauan jangka panjang: Penderita GERD mungkin perlu pemantauan jangka panjang untuk memastikan kontrol gejala dan pencegahan komplikasi. Pemeriksaan dan penilaian secara berkala oleh dokter Anda penting untuk memastikan bahwa kondisi Anda tetap terkendali dan tidak ada perubahan yang signifikan.\r\n\r\n7. Pemantauan komplikasi potensial: Jika Anda memiliki kondisi GERD yang lebih parah atau mengalami gejala yang memburuk, dokter Anda mungkin merekomendasikan pemeriksaan endoskopi atau tes lainnya untuk memeriksa kondisi esofagus dan memantau kemungkinan komplikasi seperti esofagitis, ulkus, atau penyempitan.',
                'obat' => '1. Golongan Proton Pump Inhibitor (PPI), Obat-obatan jenis ini menghambat produksi asam lambung dengan menghambat pompa proton di dalam sel lambung. \r\n*Omeprazole dapat diberikan 20-40mg 1x sehari.\r\n*Lansoprazole dapat diberikan 30mg 1x sehari.\r\n*Esomeprazole dapat diberikan 20-40mg 1x sehari.\r\n\r\n2. Golongan H2 Blocker, Obat-obatan ini mengurangi produksi asam lambung dan dapat memberikan bantuan dalam mengendalikan gejala GERD.\r\n*Ranitidine untuk kasus ulkus peptikum dapat diberikan 150mg setiap 12jam/ 2x sehari, untuk esofagitis erosif dapat diberikan 150mg setiap 6jam.\r\n*Cimetidine 800mg setiap 12jam atau 400mg setiap 6jam.',
                'priority' => '2',
            )
        );
        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'Dispepsia',
                'definisi' => 'Dispepsia adalah gangguan pencernaan yang ditandai dengan rasa tidak nyaman pada perut bagian atas serta perut terasa penuh padahal belum makan. Terkadang disertai dengan perut kembung, bersendawa, mual, dan peradangan pada lapisan lambung.',
                'solusi' => '1. Hindari makanan pedas atau berlemak, asam, kecut, minuman kafein, alkohol, berkarbonasi.\r\n\r\n2. Mengkonsumsi makanan dalam porsi kecil lebih sering sepanjang hari dapat membantu mencegah perut kembung dan ketidaknyamanan yang berlebihan.\r\n\r\n3. Mengunyah makanan dengan benar dan meluangkan waktu saat makan dapat membantu pencernaan dan mengurangi kemungkinan gejala.\r\n\r\n4. Karena stres dapat menyebabkan gejala dispepsia, menemukan teknik pengurangan stres yang efektif, seperti olahraga, meditasi, latihan pernapasan dalam, atau terapi, mungkin bermanfaat.',
                'tindak_lanjut' => 'Perawatan lanjutan untuk dispepsia melibatkan pemantauan gejala Anda, mengevaluasi efektivitas pengobatan,modifikasi gaya hidup.\r\nPerawatan tindak lanjut secara teratur memungkinkan pemantauan berkelanjutan dan memastikan bahwa rencana perawatan Anda dioptimalkan untuk mengelola dispepsia Anda secara efektif.\r\n\r\n\r\n\r\n\r\n',
                'obat' => '1. Antasida, memberikan bantuan sementara dari rasa tidak nyaman seperti nyeri, kembung, dan perut terasa penuh.\r\n*Sediaan tablet 1-2tablet, 3 hingga 4x sehari, tablet dikunyah dahulu sebelum ditelan agar terlarut dengan baik.\r\n*Sediaan syrup 10-20ml dapat diminum 4x sehari, 20menit - 1jam setelah makan dan saat sebelum tidur, maksimal 80ml/hari.\r\n\r\n2. Antagonis Reseptor Hist\r\n\r\n3. Golongan Proton Pump Inhibitor (PPI), Obat-obatan jenis ini menghambat produksi asam lambung dengan menghambat pompa proton di dalam sel lambung. \r\n*Omeprazole dapat diberikan 20-40mg 1x sehari.\r\n*Lansoprazole dapat diberikan 30mg 1x sehari.\r\n*Esomeprazole dapat diberikan 20-40mg 1x sehari.\r\n\r\n4. Prokinetik\r\n\r\n5. Antidepresan, dokter dapat meresepkan antidepresan tertentu, seperti trisiklik, dalam dosis rendah untuk membantu mengurangi gejala dispepsia yang berhubungan dengan stres atau gangguan pencernaan fungsional.',
                'priority' => '3',
            )
        );
        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'Gastroparesis',
                'definisi' => 'Gastroparesis adalah kondisi medis yang ditandai dengan penundaan atau gangguan dalam pengosongan lambung. Pada orang dengan gastroparesis, kontraksi otot lambung yang normal yang membantu mendorong makanan dari lambung ke usus halus terganggu. Hal ini dapat menyebabkan gangguan pencernaan dan gejala yang tidak nyaman.',
                'solusi' => '1. Perubahan pola makan, seperti makan makanan dalam porsi kecil dan sering, menghindari makanan berlemak dan serat tinggi, serta mengunyah makanan dengan baik.\r\n2. Mengelola stres dengan baik melalui teknik relaksasi, meditasi, olahraga, atau terapi kognitif perilaku dapat membantu mengurangi gejala gastroparesis.\r\n3. Pendekatan nutrisi: Jika gastroparesis menyebabkan kesulitan dalam mencukupi kebutuhan nutrisi, dokter atau ahli gizi dapat membantu merancang rencana makan atau memberikan suplemen nutrisi yang sesuai untuk memenuhi kebutuhan tubuh.\r\n4. Perawatan diabetes: Jika gastroparesis disebabkan oleh diabetes, pengelolaan yang baik terhadap gula darah dan perawatan diabetes yang tepat sangat penting. Mengatur kadar gula darah dengan baik dapat membantu mengurangi gejala gastroparesis.',
                'tindak_lanjut' => 'Melibatkan evaluasi medis yang komprehensif. Dokter mungkin akan memeriksa riwayat medis, gejala yang dialami, serta melakukan pemeriksaan fisik. Tes diagnostik seperti tes pencernaan dan pencitraan dapat dilakukan untuk memeriksa kecepatan pengosongan lambung, aktivitas otot lambung, dan mencari penyebab yang mendasari.',
                'obat' => '1. Obat prokinetik: membantu mempercepat gerakan makanan melalui saluran pencernaan dengan merangsang kontraksi otot lambung dan usus. Contoh obat prokinetik yang umum digunakan adalah metoklopramid (Reglan), domperidon, dan eritromisin.\r\n\r\n2. Anti-mual: dapat digunakan untuk mengurangi mual dan muntah yang sering terjadi pada gastroparesis. Contoh obat anti-mual yang mungkin diresepkan termasuk ondansetron (Zofran), proklorperazin, dan metoklopramid.\r\n\r\n3. Antasid: dapat membantu meredakan gejala seperti nyeri perut atau rasa terbakar pada gastroparesis. Obat antasid bekerja dengan menetralkan asam lambung. Contoh antasid yang umum adalah aluminium hidroksida, magnesium hidroksida, dan kalsium karbonat.\r\n\r\n4. Obat perangsang motilitas gastrointestinal: prukaloprida (Resolor) dan cisaprida dapat digunakan untuk meningkatkan motilitas atau gerakan saluran pencernaan.\r\n\r\n5. Botulinum toxin (Botox): Pada beberapa kasus yang parah, injeksi botulinum toxin dapat dilakukan pada otot lambung untuk membantu mengurangi gejala gastroparesis dengan mengendurkan otot yang terlalu tegang.',
                'priority' => '4',
            )
        );
        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'Tukak Lambung',
                'definisi' => 'Tukak lambung, juga dikenal sebagai ulkus peptikum, adalah luka atau kerusakan pada dinding lambung atau bagian atas usus dua belas jari. Tukak lambung terjadi ketika ada ketidakseimbangan antara faktor perlindungan dan faktor yang merusak dinding lambung.',
                'solusi' =>'1. Menghindari makanan atau minuman yang memperburuk gejala (seperti makanan pedas, asam, atau berlemak).\r\n2. Menghindari merokok dan alkohol.\r\n3. Mengurangi stres.\r\n4. Makan dengan porsi kecil tapi lebih sering , dan menjaga berat badan yang sehat.\r\n5. Pencegahan tukak lambung melibatkan menghindari faktor risiko yang dapat mempengaruhi dinding lambung, seperti penggunaan berlebihan obat NSAID, menghindari stres berlebihan, berhenti merokok, dan mengurangi konsumsi alkohol. Jika Anda memiliki infeksi H. pylori sebelumnya, pengobatan yang tepat dapat membantu mencegah kambuhnya infeksi.',
                'tindak_lanjut' =>  '1. Lakukan pemeriksaan rutin, ini bisa melibatkan endoskopi lanjutan atau tes lainnya untuk memeriksa penyembuhan luka atau untuk memantau keberadaan bakteri H. pylori.\r\n2. Mengikuti pengobatan yang diresepkan, pastikan untuk minum obat sesuai dengan dosis dan jadwal yang ditentukan oleh dokter.\r\n3. Perhatikan gejala dan komplikasi, jika Anda mengalami perubahan gejala atau mengalami gejala yang memburuk, segera berkonsultasi dengan dokter Anda. Jika terjadi komplikasi seperti perdarahan gastrointestinal yang ditandai dengan muntah darah atau tinja berwarna hitam, segera cari perawatan medis darurat.',
                'obat' =>   '1. Antibiotik, jika infeksi H. pylori terdeteksi sebagai penyebab tukak lambung. Seperti amoxicillin, clarithromycin, dan metronidazole diberikan selama periode tertentu.\r\n\r\n2. Prostaglandin Analog: Obat-obatan seperti misoprostol dapat digunakan untuk melindungi lapisan lambung dengan meningkatkan produksi lendir pelindung dan mengurangi produksi asam lambung. Mereka jarang digunakan sebagai pilihan pertama karena efek samping yang potensial.\r\n\r\n3. Golongan H2 Blocker:\r\n* Ranitidine 150mg setiap 12jam / 2x sehari\r\n* Cimetidine pada dewasa dosis 300-400mg diberikan 2x sehari maksimal 8 minggu pengobatan\r\n\r\n4. Penghambat Proton Pump Inhibitor (PPI):\r\n* Omeprazole dapat diberikan 20-40mh 1x sehari\r\n* Lansoprazole dapat diberikan 30mg 1x sehari\r\n* Esomeprazole dapat diberikan 20-40mh 1x sehari',
                'priority' => '5',
            )
        );
        DB::table('penyakit_solusi')->insert(
            array(
                'nama_penyakit' => 'Kanker Lambung',
                'definisi' => 'kanker akibat pertumbuhan sel lambung yang tidak normal. Biasa terjadi karena perubahan genetic. Untuk gejala awal menyerupai seperti sakit lambung biasa. Tetapi pada stadium lanjut dapat terjadi muntah darah / bab hitam',
                'solusi' => '1. Menghindari faktor risiko yang diketahui\r\n2. Menjaga pola makan yang sehat dengan makanan yang kaya serat dan rendah garam\r\n3. Mengobati infeksi H. pylori jika ada\r\n4. Berhenti merokok\r\n5. Menjaga berat badan yang sehat\r\n6. Menjalani skrining jika Anda memiliki riwayat keluarga dengan kanker lambung',
                'tindak_lanjut' => 'Endoskopi lambung untuk mengambil sampel jaringan (biopsi) untuk pemeriksaan lebih lanjut, pemeriksaan pencitraan seperti endoskopi ultrasonografi (EUS), CT scan, atau PET scan untuk menentukan sejauh mana kanker telah menyebar, serta tes darah dan tes pernapasan untuk mendeteksi infeksi H. pylori.',
                'obat' => 'Pengobatan kanker lambung bergantung pada stadium kanker, lokasi tumor, dan kondisi kesehatan secara keseluruhan. Pilihan pengobatan meliputi:\r\n1. Operasi untuk mengangkat tumor dan sebagian lambung yang terkena\r\n2. Kemoterapi untuk membunuh sel kanker\r\n3. Radioterapi untuk menghancurkan sel kanker menggunakan sinar radiasi\r\n4. Terapi target dan imunoterapi yang sedang dikembangkan sebagai opsi pengobatan yang lebih baru',
                'priority' => '6',
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('penyakit_solusi');
    }
};